-- Supabase schema for `grades` table
-- Run this in Supabase SQL editor (or via psql) to create the table.

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  date date not null,
  subject text not null,
  score int not null check (score >= 0 and score <= 100),
  inserted_at timestamptz default now()
);

create index if not exists idx_grades_date on public.grades(date);

-- Add user_id column for per-user rows and enable Row Level Security (RLS)
alter table if exists public.grades add column if not exists user_id uuid;

-- index to make per-user queries fast
create index if not exists idx_grades_user_date on public.grades(user_id, date);

-- Enable RLS and create policies so each user sees and manages only their rows.
-- Run these statements in Supabase SQL editor. Make sure you have Google Auth enabled
-- in Authentication > Providers and set Redirect URLs appropriately.

alter table public.grades enable row level security;

-- Allow authenticated users to select their own rows
create policy if not exists "Select own" on public.grades
  for select using (auth.uid() = user_id);

-- Allow authenticated users to insert rows where new.user_id equals their uid
create policy if not exists "Insert own" on public.grades
  for insert with check (auth.uid() = user_id);

-- Allow update/delete only for the owner
create policy if not exists "Update own" on public.grades
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy if not exists "Delete own" on public.grades
  for delete using (auth.uid() = user_id);

-- If you already have existing rows to migrate, set user_id accordingly or remove them.

